// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gweb/internal/logic/bizctx"
	_ "gweb/internal/logic/middleware"
)
