# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "mysql:gweb:gweb666@tcp(39.107.126.209:3306)/gweb"
        removePrefix: "gw_"
        descriptionTag: true
        noModelComment: true
