// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package chat

import (
	"gweb/api/chat"
)

type ControllerUsers struct{}

func NewUsers() chat.IChatUsers {
	return &ControllerUsers{}
}
