// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gweb/internal/dao/internal"
)

// internalChatUsersDao is internal type for wrapping internal DAO implements.
type internalChatUsersDao = *internal.ChatUsersDao

// chatUsersDao is the data access object for table gw_chat_users.
// You can define custom methods on it to extend its functionality as you wish.
type chatUsersDao struct {
	internalChatUsersDao
}

var (
	// ChatUsers is globally public accessible object for table gw_chat_users operations.
	ChatUsers = chatUsersDao{
		internal.NewChatUsersDao(),
	}
)

// Fill with you ideas below.
