// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gweb/internal/dao/internal"
)

// internalChatGroupMsgDao is internal type for wrapping internal DAO implements.
type internalChatGroupMsgDao = *internal.ChatGroupMsgDao

// chatGroupMsgDao is the data access object for table gw_chat_group_msg.
// You can define custom methods on it to extend its functionality as you wish.
type chatGroupMsgDao struct {
	internalChatGroupMsgDao
}

var (
	// ChatGroupMsg is globally public accessible object for table gw_chat_group_msg operations.
	ChatGroupMsg = chatGroupMsgDao{
		internal.NewChatGroupMsgDao(),
	}
)

// Fill with you ideas below.
